# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
  - page: 主页
    url: /
    icon:
  - page: 时间轴
    url: /archives/
    icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: "./img/head-img.jpg"
  url: "https://space.bilibili.com/537935205"

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: true
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
  <p>
      欢迎来到GVZ的博客！
      请务必认真阅读<a href="https://gvzgithub.github.io/%E7%94%A8%E6%88%B7%E5%8D%8F%E8%AE%AE/" target="_blank">用户协议</a>和<a href="https://gvzgithub.github.io/%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96/" target="_blank">隐私政策</a>后再阅读博客的其他文章，
      然后可以查看<a href="https://gvzgithub.github.io/%E5%85%B3%E4%BA%8E%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/" target="_blank">使用指南</a>获得更多帮助
  </p>

## 社交设置
social:
  - name: Github
    icon: git
    href: //github.com/gvzgithub
  - name: RSS
    icon: rss
    href: /atom.xml

## 文章分类设置
cate_config:
  show_count: true
  show_current: true

## 文章归档设置
arch_config:
  type: "monthly"
  format: "YYYY年MM月"
  show_count: true
  order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: "#444"
  outlineMethod: "block"
  outlineColour: "#FFDAB9"
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - GVZLINK3: https://link3.cc/gvzlink/
  - GVZBILI: https://space.bilibili.com/537935205

# 主题自定义个性化配置

## 网站宣传语
branding: 欢迎来到GVZ的个人网站！

## 设置banner背景图片
banner:
  img: https://s1.imagehub.cc/images/2024/02/03/54b452f0f636cfe249624d1e07f88e04.jpeg
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome: 

## 文章过期提醒功能
warning:
  days: 365
  text: "本文于%d天之前发表，文中内容可能已经过时。"

## 文章内声明
declaration:
  enable: true
  title: "转载声明"
  tip: |-
    商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">GVZ</a>

## 文章打赏
reward:
  alipay: ""
  wepay: ""
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## utterances评论
utterances:
  enable: true
  repo: gvzgithub/gvzgithub.github.io
  issueTerm: pathname
  issueNumber: 
  theme: github-light
  label: 
  cdn: 

## Valine评论
valine:
  enable: false
  appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
  appKey: erIpQac4azoCmgfBB7Dl9maa
  placeholder: 说点什么吧
  notify: false
  verify: true
  avatar: mm
  meta: nick,mail
  pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
  enable: false
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  perPage:
  distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

## 网站访客统计
visit_counter:
  site: false
  page: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2024
robot: "all" ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.3.0
